#!/usr/bin/env python3
import json
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

CURRENCY = "USD"

req = Request("https://blockchain.info/ticker")
try:
    response = urlopen(req)
    data = json.loads(response.read())
    print(data[CURRENCY]['last'])
except HTTPError as e:
    print('x')
    #print('Error code: ', e.code)
except URLError as e:
    print('x')
    #print('Reason: ', e.reason)
