rules:
  # move incomplete downloads older > 30 days into the trash
  - folders: ~/Downloads
    filters:
      - extension:
          - download
          - crdownload
          - part
      - lastmodified:
          days: 30
          mode: older
    actions:
      - trash

  # delete empty files from downloads and desktop
  - folders: 
      - ~/Downloads
      - ~/Desktop
    filters:
      - filesize: 0
    actions:
      - trash
