#!/bin/sh
lokk() {
    lock -gpf Roboto-Mono -t "magic word!?!" -- scrot -z
}

case "$1" in
    lock)
        lokk
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lokk && systemctl suspend
        ;;
    hibernate)
        lokk && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
