#!/usr/bin/env bash


if [ ! -z ${1} ] && [ ${1} = '-d' ];then
    wget -q -O- http://feeds.feedburner.com/neueswort\?format\=xml | sed -n -r 's/.*<description><!\[CDATA\[<p>(.*)<\/p>/\1/p' | head -n 1
    exit 0;
fi

wget -q -O- http://feeds.feedburner.com/neueswort\?format\=xml | sed -n -r 's/.*<title>(\w+)<\/title>/\1/p' | head -n 1
