if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/bundle')

" UI
Plug 'itchyny/lightline.vim'
Plug 'chriskempson/base16-vim'
Plug 'mike-hearn/base16-vim-lightline'
Plug 'junegunn/goyo.vim'

Plug 'flrnprz/candid.vim'
Plug 'ayu-theme/ayu-vim'
Plug 'ayu-theme/ayu-vim-airline'
Plug 'Yggdroot/indentLine'

Plug 'majutsushi/tagbar'
Plug 'mbbill/undotree'
" Plug 'ryanoasis/vim-devicons'
Plug 'kien/rainbow_parentheses.vim'
Plug 'mhinz/vim-startify'
Plug 'junegunn/fzf.vim'
Plug 'editorconfig/editorconfig-vim'

" Movement
Plug 'easymotion/vim-easymotion'

Plug 'jremmen/vim-ripgrep',                 { 'on': 'Rg' }
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-surround'
" Track the engine.
Plug 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plug 'honza/vim-snippets'

" Languages
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neoclide/coc.nvim', {'tag': '*', 'branch': 'release'}
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

Plug 'tpope/vim-markdown',                  { 'for': 'markdown' }
Plug 'JamshedVesuna/vim-markdown-preview'
Plug 'fatih/vim-go',                        { 'for' : 'go' }
Plug 'rust-lang/rust.vim',                  { 'for' : 'rust' }
Plug 'cespare/vim-toml',                    { 'for' : 'toml' }
Plug 'avakhov/vim-yaml'

" Git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

call plug#end()
