# Cursor color.
cursor #fb94ff

# Color of text under the cursor.
# cursor_text_color #000000

# Default cursor shape.
# cursor_shape block

# Cursor thickness.
# cursor_beam_thickness 3
# cursor_underline_thickness 3

# Interval in seconds at which to blink the cursor.
cursor_blink_interval 0
cursor_stop_blinking_after 15.0
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05

copy_on_select yes
