#!/usr/bin/env bash
JIRABIN="/home/dvogt/.scripts/jira"

[ ! -z $1 ] && [ "$1" == "rofi" ] && \
    CMD="$(echo -e "start\nlog\nfinish" | rofi -dmenu -p "JIRA")"

([ ! -z $CMD ] && [ "$CMD" == "start" ]) || ([ ! -z $1 ] && [ "$1" == "start" ]) && \
    $JIRABIN start $($JIRABIN list -q "Sprint in openSprints() AND assignee = $USER AND status = 'Open'" | dmenu | rg -o '^[^:]+') && \
    exit 0;

([ ! -z $CMD ] && [ "$CMD" == "log" ]) || ([ ! -z $1 ] && [ "$1" == "log" ]) && \
   /usr/local/bin/st -e $JIRABIN worklog add $($JIRABIN list -q "Sprint in openSprints() AND assignee = $USER AND status = 'In Progress'" | dmenu | rg -o '^[^:]+') # -m "$3" -T $2 # --noedit
