#!/usr/bin/env bash
# see https://help.github.com/articles/changing-author-info/

# git shortlog -sne

# git clone --bare https://github.com/user/reponame.git FIXME
# cd FIXME

# git push --force --tags origin 'refs/heads/*'

git filter-branch --env-filter $'
OLD_EMAILS="
d.vogt@deos-ag.com
"
CORRECT_NAME="dvogt23"
CORRECT_EMAIL="divogt@live.de"
for EMAIL in ${OLD_EMAILS}; do
    if [ "$GIT_COMMITTER_EMAIL" = "$EMAIL" ]; then
        export GIT_COMMITTER_NAME="$CORRECT_NAME"
        export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
    fi
    if [ "$GIT_AUTHOR_EMAIL" = "$EMAIL" ]; then
        export GIT_AUTHOR_NAME="$CORRECT_NAME"
        export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
    fi
done
' --tag-name-filter cat -- --branches --tags
