#!/usr/bin/env bash

tmux_popup_session_name="_popup"

if [ "$(tmux display-message -p -F "#{session_name}")" = "${tmux_popup_session_name}" ]; then
  tmux detach-client
else
  tmux popup -d '#{pane_current_path}' -xC -y100 -w100% -h50% -E "tmux new-session -A -s ${tmux_popup_session_name}"
fi
