#!/bin/sh
lock() {
    i3lock-fancy #--color "$bg-color"
}

case "$1" in
    lock)
        i3lock-fancy-rapid 5 3
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend
        #i3lock-fancy && systemctl suspend
        ;;
    hibernate)
        i3lock-fancy && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
