# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character" ▻ ➛
success_symbol = "[⋅⋅➤](bold green)"
error_symbol = "[⋅!➤](bold red)"
vicmd_symbol = "[⋅⋅➤](bold yellow)"

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[++\($count\)](green)'

[jobs]
symbol = "★"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[gcloud]
disabled = true

[directory]
truncation_length = 12
truncate_to_repo = false

[hostname]
ssh_only = false
prefix = "10218;"
suffix = " 10219;"
trim_at = ".companyname.com"
disabled = true
