# Additional git repositories to pull
#git_repos = [
#    "~/src/*/",
#    "~/.config/something"
#]

# Disable specific steps - same options as the command line flag
disable = ["git_repos", "gem", "flutter"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Run inside tmux
# run_in_tmux = true

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Arguments to pass Git when pulling Repositories
#git_arguments = "--rebase --autostash"

# Arguments to pass yay when updating packages
[linux]
yay_arguments = "--nodevel --ignore=jdk8"

# Do not set the terminal title
#set_title = false
# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
# [commands]
# "Update rust-analyzer" = ". $HOME/.scripts/update-rust-analyzer"

# Cleanup temporary or old files
# cleanup = true

